apiVersion: apps/v1  # Specifies the API version for the Deployment resource
kind: Deployment  # Defines the resource type as a Deployment
metadata:
  name: comments-depl  # Name of the Deployment
spec:
  replicas: 1  # Number of pod replicas to maintain
  selector:
    matchLabels:
      app: comments 
  template:
    metadata:
      labels:
        app: comments  # Labels applied to the pod, must match selector labels
    spec:
      containers:
        - name: comments  # Name of the container
          image: akshayvishwakarma00008/comments  # Docker image to be used for this container
---

apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  selector:
    app: comments
  ports:
    - name: comments
      protocol: TCP
      port: 4001
      targetPort: 4001