apiVersion: apps/v1  # Specifies the API version for the Deployment resource
kind: Deployment  # Defines the resource type as a Deployment
metadata:
  name: moderation-depl  # Name of the Deployment
spec:
  replicas: 1  # Number of pod replicas to maintain
  selector:
    matchLabels:
      app: moderation 
  template:
    metadata:
      labels:
        app: moderation  # Labels applied to the pod, must match selector labels
    spec:
      containers:
        - name: moderation  # Name of the container
          image: akshayvishwakarma00008/moderation  # Docker image to be used for this container
---

apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  selector:
    app: moderation
  ports:
    - name: moderation
      protocol: TCP
      port: 4003
      targetPort: 4003